### ISSUE TITLE
Serialization of Closure issue

### ISSUE THREAD

**Issue by fxpage** [omnilight/yii2-shopping-cart#25]
I got this issue in line 122 of ShoppingCart.php.

'Exception 'Exception' with message 'Serialization of 'Closure' is not allowed'

in /Volumes/MACDATA/Work/Aljazeera/vendor/omnilight/yii2-shopping-cart/ShoppingCart.php:122'

Please review the code and it would be great if you can handle this exception.

I have used your cart as global application component.

when I run the code `\Yii::$app->cart->put($model, 1);` in my viewcontroller, it throws the exception.

**Comment by omnilight** [comment]
I've closed previous similar issue, because you did not provide proper example of your code. You should know, that ShoppingCart serialises it's positions to store them to the session, so, if one of your position stores closure in one of it's properties, you will get this error. So you should either do not use closures in positions (for example use special model) or implement proper __sleep method for your object:
http://php.net/manual/en/language.oop5.magic.php#object.sleep
